<?php
$template =
'<article class="post">
  <h2>%s</h2>
  <time>%s</time>
  <p>%s</p>
  <a href="/posts/view/%s" class="read-more">Read More</a>
  <p>Posted By: <a href="%s" rel="author">%s</a></p>
</article>';

foreach ($this->Posts as $post) {
  printf($template, 
         $post['title'], $post['created'], $post['content'], 
         $post['slug'], $post['author_id'], $post['author']['first_name']);
}

?>
