<?php
$postTemplate =
'<article class="post">
  <h2>%s</h2>
  <time>%s</time>
  <p>%s</p>
  <a href="%s" rel="author">%s</a>
</article>';

$commentTemplate = 
'<section>
  <a href="/author/%s">%s</a>
  <p>%s</p>
</section>';

$post = $this->Post;
printf($postTemplate, 
       $post['title'], $post['created'], $post['content'], 
       $post['author_id'], $post['author']['first_name']);

echo '<footer>';

foreach ($post['comments'] as $comment) {
  printf($commentTemplate, 
         $comment['author_id'], $comment['author']['first_name'], $comment['body']);
}

echo '</footer>';
?>
