<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Simple Zend Blog Demo</title>
    <meta name="author" content="Jordan Schatz jordan@noionlabs.com" />

    <!-- HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link href="/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/css/styles.css" rel="stylesheet" />
  </head>
  
  <body>
    <!-- Topbar
    ================================================== -->
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="/">Simple Zen(d) Blog</a>
          <form action="/authors/login" class="pull-right" method="POST">
            <input name="first_name" class="input-small" type="text"     
                   placeholder="First Name" />
            <input name="last_name"  class="input-small" type="text" 
                   placeholder="Last Name"/>
            <button class="btn" type="submit">Sign in</button>
          </form>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <?= $this->layout()->content; ?>
      </div>

      <footer>
        <p>&copy; Noionλabs 2011</p>
      </footer>

    </div> <!-- /container -->


  </body>
</html>